"""
====================================================================
 DocuMate108 v5.0 / 108 -- Birth Registration
====================================================================

 108 is the convergence. Two lineages become one system.

 Z brought the database migration: Excel ripped out, PostgreSQL
 in, Power BI connected, auto-detection loop added. The data
 layer was solved.

 X brought the engine migration: Python's docxtpl rendering
 replaced by Word's native Mail Merge via COM automation.
 Batched execution (250 records per batch) solved the hanging
 problem on large volumes. 1,440 records in ~52 seconds.

 108 fuses both. Data comes from PostgreSQL. Documents are
 generated by Word's Mail Merge engine. The best data layer
 married to the fastest document engine.

--------------------------------------------------------------------
 HOW IT WORKS
--------------------------------------------------------------------

 The challenge: Word's Mail Merge expects a flat file data
 source (Excel, CSV, Access). It cannot connect to PostgreSQL
 directly.

 The solution: DocuMate108 writes the filtered database records
 to a temporary Excel file, points Word's Mail Merge at it,
 processes in batches of 250, combines the batch outputs into
 one final document, then cleans up the temp file.

 Pipeline:
   PostgreSQL --> load_data() --> list of dicts
     --> temp Excel file (only filtered records)
       --> Word Mail Merge (batched, 250 per batch)
         --> temp .docx per batch
           --> combined into one final .docx
             --> temp files cleaned up

 Because the temp Excel contains ONLY the filtered "IN PROCESS"
 records, the Mail Merge range is always 1 to N. No row-mapping
 gymnastics needed -- every row in the temp file is a valid record.

--------------------------------------------------------------------
 WHAT CHANGED FROM Z AND X
--------------------------------------------------------------------

 From Z (kept):
   - __init__ with db_config, PostgreSQL connection
   - validate_environment()
   - load_data() with SQL join across three tables
   - update_sql_status() with batch UPDATE
   - run() pipeline
   - start() with auto-detection loop
   - Entry point with db_config and auto_detect

 From X (adapted):
   - generate_and_merge_documents() rewritten to use Word's
     native Mail Merge engine via COM automation
   - Batched execution (250 records per batch)
   - DispatchEx for fresh Word instance
   - AutomationSecurity = 3 to suppress dialogs
   - Temp batch files combined via InsertFile
   - All temp files cleaned up in finally block

 New in 108:
   - Temp Excel bridge: database records written to a temporary
     .xlsx file as the Mail Merge data source
   - Simplified record range: temp file has only filtered records,
     so range is always 1 to len(data) -- no merge_record mapping

 Removed from Z:
   - add_page_break() (Word handles breaks via InsertBreak)
   - docxtpl rendering (replaced by Word Mail Merge)
   - docxcompose merging (replaced by Word InsertFile)
   - ProcessPoolExecutor parallel processing (Word handles it)
   - process_record() standalone function (not needed)

--------------------------------------------------------------------
 TEMPLATE REQUIREMENTS
--------------------------------------------------------------------

 108 requires a Word Mail Merge template (.docx), NOT a docxtpl
 template. The merge fields in the template must match the
 column names produced by load_data():

   Serial, Name, Sex, When_and_where_born,
   Name_of_the_Father, Name_of_the_Mother,
   Description_and_residence_of_informant,
   Registration_date, MHA_File_And_date,
   Signing_Authority_Name, Signing_Authority_Name_Designation,
   year

 Use Word's "Insert Merge Field" to place these in the template.

--------------------------------------------------------------------
 PERFORMANCE
--------------------------------------------------------------------

 1,440 records:
   - Manual process:              ~126 hours
   - DocuMate v3 (docxtpl):       ~3.5 minutes
   - DocuMateX (batched MM):      ~52 seconds
   - DocuMate108 (DB + batched MM): ~52 seconds + DB query time

--------------------------------------------------------------------
 KNOWN LIMITATIONS
--------------------------------------------------------------------

 - Database credentials are hardcoded (no config file or env vars)
 - No reconnection logic if the database connection drops
 - Popups are Windows-only (ctypes.windll)
 - Requires Microsoft Word desktop installed (COM automation)
 - Windows only (win32com / pythoncom)
 - Auto-detect mode has no graceful shutdown beyond Ctrl+C
 - Word's "Select Table" dialog may appear on template open
   if the template has a saved data source link
 - Temp files are written during processing and cleaned up after.
   If the process crashes mid-batch, leftover temp files may remain.

--------------------------------------------------------------------
 REQUIREMENTS
--------------------------------------------------------------------

 pip install psycopg2 pandas openpyxl pywin32
 Microsoft Word desktop must be installed.

====================================================================
"""


import pandas as pd                          # For temp Excel bridge (DB records -> .xlsx)
import time                                  # For tracking execution time and poll intervals
import os                                    # For building file paths
import sys                                   # For detecting .exe vs .py execution
import ctypes                                # For Windows popup messages
from datetime import datetime                # For timestamps in filenames
import psycopg2                              # PostgreSQL database driver
import datetime as dt                        # For date operations in SQL updates

try:
    import pythoncom                         # COM threading initialisation
    import win32com.client                   # COM automation for Microsoft Word
except ImportError:
    print("❌ pywin32 is required for Mail Merge mode.")
    print("   Install it with: pip install pywin32")
    sys.exit(1)


# Word constants (numeric values for COM calls)
WD_SEND_TO_NEW_DOCUMENT = 0
WD_DO_NOT_SAVE_CHANGES = 0
WD_FORMAT_DOCUMENT_DEFAULT = 16   # .docx


# ====================================================================
# BirthRegistrationProcessor
# --------------------------------------------------------------------
# Z's class structure with X's document generation engine.
#
# Data layer: PostgreSQL (from Z)
#   - __init__ owns the database connection
#   - load_data() runs SQL join, returns list of dicts
#   - update_sql_status() batch-updates status to PRINTED
#
# Document layer: Word Mail Merge via COM (from X)
#   - generate_and_merge_documents() writes records to temp Excel,
#     drives Word's Mail Merge in batches of 250, combines output
#
# Control layer: auto-detection loop (from Z)
#   - start() wraps run() with optional polling loop
# ====================================================================

class BirthRegistrationProcessor:

    def __init__(self, db_config, template_path, output_folder, update_existing=False, auto_detect=False, poll_interval=300):
        """
        Sets up the processor.

        - db_config:       Dictionary with database connection parameters
                           (host, database, user, password, port, sslmode)
        - template_path:   Path to the Word Mail Merge template (.docx)
        - output_folder:   Where the merged output will be saved
        - update_existing: Whether to update database after generation
                           (overridden by user prompt during run)
        - auto_detect:     If True, runs in a loop checking for new
                           records every poll_interval seconds
        - poll_interval:   Seconds between auto-detection checks
                           (default: 300 = 5 minutes)
        """

        self.conn = psycopg2.connect(**db_config)
        self.cur = self.conn.cursor()
        self.template_path = template_path
        self.output_folder = output_folder
        self.data = None                     # Will hold list of record dicts from DB
        self.update_existing = update_existing
        self.auto_detect = auto_detect
        self.poll_interval = poll_interval


    def validate_environment(self) -> bool:
        """
        Pre-flight check before DocuMate does anything.

        Validates:
        - Template file exists (crashes mid-loop without this)
        - Output folder exists (creates it if not)

        Called at the top of run() so failures are caught
        early with a clear message, not halfway through
        processing 300 records.
        """

        if not os.path.exists(self.template_path):
            ctypes.windll.user32.MessageBoxW(
                0,
                f"❌ Template not found:\n{self.template_path}",
                "DocuMate",
                0
            )
            return False

        if not os.path.exists(self.output_folder):
            print(f"\nDocuMate : 📂 Output folder '{self.output_folder}' does not exist. Creating it...")
            os.makedirs(self.output_folder)

        return True


    def load_data(self):
        """
        Step 1: Pull records from the database.

        Runs a SQL query that:
        - Joins applicant -> ministry of home affairs -> IB authority
        - Filters to STATUS = 'IN PROCESS' at the database level
        - Orders by serial number
        - Returns only the fields needed for the Word template

        The raw SQL rows are then converted into a list of
        dictionaries with keys matching the merge field names
        in the Word Mail Merge template.
        """

        self.cur.execute("""
            SELECT
                a.file_number, 
                a.serial,
                UPPER(a.name),
                UPPER(a.sex),
                a.birth_date,
                UPPER(CONCAT(a.place, ', ', a.state_code)) AS place_of_birth,
                UPPER(a.name_of_father),
                UPPER(a.name_of_mother),
                UPPER(CONCAT(a.address_line_1, ', ',a.address_line_2, ', ',a.address_line_3)) AS address,
                a.registration_date,
                b.mha_file_number,
                b.mha_date,
                UPPER(ib.ib_staff_authority_name) AS signing_authority_name,
                UPPER(CONCAT(ib.ib_staff_authority_name, ', ',ib.ib_staff_authority_designation)) AS authority_name_designation
            FROM applicant a
                JOIN ministryofhomeaffairs b
                    ON a.mha_file_number = b.mha_file_number
                LEFT JOIN ib_authority ib
                    ON a.ib_staff_authority_id = ib.ib_staff_authority_id
            WHERE UPPER(a.status) = 'IN PROCESS'
            ORDER BY a.serial;
        """)

        rows = self.cur.fetchall()

        # If no records match, show a popup and stop
        if not rows:
            msg = (
                "📝 No records found with status 'IN PROCESS'.\n\n"
                "🧠 Powered by ENN -- Fuelled by curiosity, refined by data-driven clarity."
            )
            ctypes.windll.user32.MessageBoxW(0, msg, "DocuMate", 0)

        # Convert each SQL row into a dictionary with keys matching
        # the Word Mail Merge field names.
        # Serial 123 -> "123/2025", dates -> "dd/mm/yyyy",
        # names -> UPPERCASE, address fields -> concatenated
        #
        # "year" is injected as a standalone key so the Word template
        # can use it in file numbers or anywhere the current year
        # appears. This prevents the hardcoded-year bug that caused a
        # missed update during the 2025->2026 transition.
        current_year = dt.datetime.now().year

        self.data = [
            {
                "File_Number": r[0],
                "Serial": str(r[1]) +"/"+str(current_year),
                "Name": r[2],
                "Sex": r[3],
                "When_and_where_born":(r[4].strftime("%d/%m/%Y") if hasattr(r[4], "strftime") else str(r[4])) + ", " + r[5],
                "Name_of_the_Father": r[6],
                "Name_of_the_Mother": r[7],
                "Description_and_residence_of_informant": r[8],
                "Registration_date": r[9].strftime("%d/%m/%Y"),
                "MHA_File_And_date": r[10] + ", " + (r[11].strftime("%d/%m/%Y") if hasattr(r[11], "strftime") else str(r[11])),
                "Signing_Authority_Name": r[12],
                "Signing_Authority_Name_Designation": r[13]
            }
            for r in rows
        ]
        return self.data


    def generate_and_merge_documents(self, merged_filename="merged_birth_cert.docx"):
        """
        Step 2: Generate Word documents using Microsoft Word's
        native Mail Merge engine via COM automation.

        Because Word's Mail Merge cannot connect to PostgreSQL
        directly, this method bridges the gap:

        1. Writes self.data (list of dicts from the database)
           to a temporary Excel file. Only filtered "IN PROCESS"
           records go into the temp file, so every row is valid.

        2. Opens the Word Mail Merge template via COM automation
           (DispatchEx for a fresh Word instance).

        3. Connects the template's Mail Merge to the temp Excel
           file as its data source.

        4. Executes the merge in batches of 250 records to prevent
           Word from hanging on large volumes. Each batch produces
           a temporary .docx file.

        5. Combines all batch files into one final document using
           Word's InsertFile with section breaks between batches.

        6. Cleans up all temp files (Excel + batch .docx files).

        Because the temp Excel contains only the filtered records,
        the Mail Merge range is always 1 to N. No row-mapping
        or continuity checks needed.
        """

        if not self.data:
            print("DocuMate : ⚠️ No records found for merging.")
            return

        total_records = len(self.data)

        # Ensure output folder exists
        if not os.path.exists(self.output_folder):
            print(f"DocuMate : 📂 Creating output folder '{self.output_folder}'...")
            os.makedirs(self.output_folder)

        # --- Write filtered records to a temporary Excel file ---
        # This is the bridge between PostgreSQL and Word Mail Merge.
        # The temp file lives in the output folder and gets cleaned
        # up in the finally block.
        temp_excel_path = os.path.abspath(
            os.path.join(self.output_folder, "__temp_mail_merge_source.xlsx")
        )
        temp_sheet_name = "DocuMateData"

        df = pd.DataFrame(self.data)
        df.to_excel(temp_excel_path, sheet_name=temp_sheet_name, index=False, engine="openpyxl")

        template_abs = os.path.abspath(self.template_path)
        output_path = os.path.abspath(os.path.join(self.output_folder, merged_filename))

        # Batch setup: Word chokes on 1000+ records in a single Execute
        first_record = 1
        last_record = total_records
        batch_size = 100

        batches = []
        for i in range(first_record, last_record + 1, batch_size):
            batch_end = min(i + batch_size - 1, last_record)
            batches.append((i, batch_end))

        word = None
        main_doc = None
        final_doc = None
        temp_files = []

        try:
            pythoncom.CoInitialize()

            word = win32com.client.DispatchEx("Word.Application")
            word.Visible = True
            word.DisplayAlerts = 0
            word.AutomationSecurity = 3  # msoAutomationSecurityForceDisable

            time.sleep(1)

            main_doc = word.Documents.Open(template_abs, ReadOnly=True, AddToRecentFiles=False)
            time.sleep(0.5)

            sheet = temp_sheet_name.replace("'", "''")

            print("DocuMate : 🔗 Connecting data source. Please approve the action in Word if prompted and wait for document generation to complete...")
            main_doc.MailMerge.OpenDataSource(
                Name=temp_excel_path,
                ConfirmConversions=False,
                ReadOnly=True,
                LinkToSource=True,
                AddToRecentFiles=False,
                Revert=False,
                Connection=(
                    "Provider=Microsoft.ACE.OLEDB.12.0;"
                    f"Data Source={temp_excel_path};"
                    'Extended Properties="Excel 12.0 Xml;HDR=YES;IMEX=1";'
                ),
                SQLStatement=f"SELECT * FROM [{sheet}$]",
                SubType=0
            )
            print("DocuMate : ✅ Data source connected successfully. Please wait while documents are generated...")

            time.sleep(0.5)

            main_doc.MailMerge.MainDocumentType = 0
            main_doc.MailMerge.Destination = WD_SEND_TO_NEW_DOCUMENT
            main_doc.MailMerge.SuppressBlankLines = True

            # Process each batch
            for batch_num, (batch_start, batch_end) in enumerate(batches, start=1):
                main_doc.MailMerge.DataSource.FirstRecord = int(batch_start)
                main_doc.MailMerge.DataSource.LastRecord = int(batch_end)
                main_doc.MailMerge.Execute(Pause=False)

                time.sleep(0.5)

                merged_doc = word.ActiveDocument

                temp_path = os.path.abspath(
                    os.path.join(self.output_folder, f"__temp_batch_{batch_num}.docx")
                )
                merged_doc.SaveAs2(temp_path, FileFormat=WD_FORMAT_DOCUMENT_DEFAULT)
                temp_files.append(temp_path)

                try:
                    merged_doc.Close(False)
                except Exception:
                    pass
                merged_doc = None

                batch_count = batch_end - batch_start + 1

            # Close the template before combining
            try:
                main_doc.Close(False)
            except Exception:
                pass
            main_doc = None

            # Combine all batch files into one final document
            if len(temp_files) == 1:
                # Only one batch -- just move it to the final path
                import shutil
                shutil.move(temp_files[0], output_path)
                temp_files = []
            else:
                final_doc = word.Documents.Open(os.path.abspath(temp_files[0]))

                for i, temp_file in enumerate(temp_files[1:], start=2):
                    rng = final_doc.Range(final_doc.Content.End - 1, final_doc.Content.End - 1)
                    rng.InsertBreak(7)  # wdSectionBreakNextPage
                    rng = final_doc.Range(final_doc.Content.End - 1, final_doc.Content.End - 1)
                    rng.InsertFile(os.path.abspath(temp_file))

                final_doc.SaveAs2(output_path, FileFormat=WD_FORMAT_DOCUMENT_DEFAULT)

            print(f"\nDocuMate : ✅ Generated and merged {total_records} documents and saved in:\n📂 {output_path}")

        except Exception as e:
            print(f"\n⚠️ DocuMate : Mail Merge error -- {e}")
            raise

        finally:
            # Close everything safely
            try:
                if final_doc is not None:
                    final_doc.Close(False)
            except Exception:
                pass

            try:
                if main_doc is not None:
                    main_doc.Close(False)
            except Exception:
                pass

            try:
                if word is not None:
                    word.Quit()
            except Exception:
                pass

            try:
                pythoncom.CoUninitialize()
            except Exception:
                pass

            # Clean temp batch files
            for f in temp_files:
                try:
                    if os.path.exists(f):
                        os.remove(f)
                except Exception:
                    pass

            # Clean temp Excel data source
            try:
                if os.path.exists(temp_excel_path):
                    os.remove(temp_excel_path)
            except Exception:
                pass


    def update_sql_status(self):
        """
        Step 3 (optional): Mark processed records as "PRINTED"
        in the database.

        Safety measures:
        - Checks if date_issued column exists; creates it if not
        - Processes in batches of 300 to avoid timeout issues
        - Only updates rows still marked "IN PROCESS"
          (prevents double-updating if run twice)
        - Rolls back the entire transaction on failure
        """
        if not self.data:
            print("⚠️ DocuMate : No data to update.")
            return

        try:
            # Remove any query timeout for large batches
            self.cur.execute("SET statement_timeout = 0;")

            # Fail-safe: make sure date_issued column exists.
            # If someone set up the DB without it, this creates
            # it automatically instead of crashing.
            self.cur.execute("""
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'applicant'
                AND column_name = 'date_issued';
            """)
            if not self.cur.fetchone():
                self.cur.execute("ALTER TABLE applicant ADD COLUMN date_issued DATE;")
                self.conn.commit()

            today = dt.date.today()

            # Get serial numbers of records processed in THIS run only
            serials = [int(row["Serial"].split("/")[0]) for row in self.data]

            # Update in batches of 300 to avoid hitting database
            # timeouts or memory limits on large datasets
            batch_size = 300
            total_updated = 0

            for i in range(0, len(serials), batch_size):
                batch = serials[i:i + batch_size]

                # WHERE clause double-checks status is still "IN PROCESS"
                # to prevent re-marking records already updated
                self.cur.execute(
                    """
                    UPDATE applicant
                    SET status = 'PRINTED',
                        date_issued = %s
                    WHERE serial = ANY(%s)
                    AND coalesce(upper(status),'') = 'IN PROCESS';
                    """,
                    (today, batch)
                )

                total_updated += self.cur.rowcount
                self.conn.commit()

            print(f"✅ DocuMate : Database updated successfully ({total_updated} records).")

        except Exception as e:
            # Roll back so no partial updates are left in the database
            self.conn.rollback()
            print(f"❌ DocuMate : DB update failed -- {e}")



    def run(self):
        """
        Runs the full pipeline once:
        Load from DB -> Generate via Mail Merge -> (Optional) Update DB

        Same structure as Z's run(), but document generation now
        uses Word's native Mail Merge engine instead of docxtpl.
        """
        try:
            # --- Pre-flight check ---
            if not self.validate_environment():
                return

            # --- Load from database ---
            print("DocuMate : 📄 Reading database records...")
            self.load_data()
            if not self.data:
                return
            print("DocuMate : 🔍 Searching for new records...")
            print(f"DocuMate : 📝 Found {len(self.data)} new records to populate.\n")

            total_start = time.time()

            # --- Generate via Word Mail Merge ---
            print("DocuMate : ⚙️  Initializing Microsoft Word Mail Merge engine...\n")
            merge_start = time.time()
            self.generate_and_merge_documents(
                merged_filename=f"DocuMateO_BIRTH_REGISTRATION_{datetime.now().strftime('%d%m%Y_%H%M%S')}.docx"
            )
            merge_time = time.time() - merge_start
            print(f"\nDocuMate : ✅ Generated and merged {len(self.data)} documents")
            print(f"DocuMate : ⚡ Mail Merge completed in {merge_time:.2f} seconds.\n")

            # --- Ask user: update database? ---
            user_choice = input(
                f"DocuMate : Do you want me to mark the statuses as PRINTED for {len(self.data)} records? (yes/no): "
            ).strip().lower()
            self.update_existing = user_choice in ("yes", "y")

            # --- (Optional) Update database ---
            update_text = ""
            db_time = 0.0
            if self.update_existing:
                print("\nDocuMate : ⏳ Updating database statuses...\n")
                db_start = time.time()
                self.update_sql_status()
                db_time = time.time() - db_start
                update_text = f" and updated Database in {db_time:.2f} seconds"

            # --- Final summary popup ---
            total_time = time.time() - total_start

            msg = (
                f"✅ DocuMate : Mission accomplished!\n"
                f"✅ Generated {len(self.data)} documents successfully{update_text}.\n"
                f"✅ Total time taken: {total_time:.2f} seconds.\n\n"
                "⚡ Powered by Word Mail Merge + PostgreSQL.\n"
                "🧠 Powered by ENN -- Fuelled by curiosity, refined by data-driven clarity."
            )
            ctypes.windll.user32.MessageBoxW(0, msg, "DocuMate", 0)

        except PermissionError:
            msg = (
                "❌ I cannot engage the populate launch because a required file is open.\n"
                "Please close it and try again later.\n\nMission aborted."
            )
            ctypes.windll.user32.MessageBoxW(0, msg, "DocuMate", 0)

        except Exception as e:
            msg = (
                f"⚠️ DocuMate encountered an unexpected error:\n{e}\n\n"
                "🧠 Powered by ENN -- Fuelled by curiosity, refined by data-driven clarity."
            )
            ctypes.windll.user32.MessageBoxW(0, msg, "DocuMate", 0)


    def start(self):
        """
        Entry point -- decides how DocuMate runs:

        - auto_detect = False -> runs once and exits (same as v3/v4.0)
        - auto_detect = True  -> runs in a loop, checking for new
          records every poll_interval seconds. Acts like a
          lightweight background service. Stops on Ctrl+C.
        """

        if not self.auto_detect:
            # Single run -- same behaviour as previous versions
            self.run()
            return

        # Auto-detection loop
        print("DocuMate : 🤖 DocuMate auto-detection enabled.")
        print(f"DocuMate : ⏳ Checking for new records every {self.poll_interval} seconds...\n")

        while True:
            try:
                self.run()
                time.sleep(self.poll_interval)

            except KeyboardInterrupt:
                print("\n🛑 DocuMate: Auto-detection stopped by user.")
                break

            except Exception as e:
                print(f"⚠️ Auto-detection error: {e}")
                time.sleep(self.poll_interval)


# ====================================================================
# ENTRY POINT
# --------------------------------------------------------------------
# Database connection parameters passed to the class. No Excel path
# needed -- records come from PostgreSQL. Template must be a Word
# Mail Merge template with merge fields matching load_data() keys.
#
# auto_detect=True + poll_interval=30 means it will keep running,
# checking for new records every 30 seconds.
#
# Expected folder structure:
#
#   base_dir/
#   ├── templates/DOCUMENT_TEMPLATE_FILE_MM.docx  <- Mail Merge template
#   └── output_files/                             <- merged output
#
# ====================================================================

if __name__ == "__main__":

    print("\n🚀 ENN : Initializing hypersonic missile DocuMate launch...")
    print("DocuMate : Alright ENN, initializing populate launch 🚀\n")

    # Resolve base directory (same logic as v2/v3)
    base_dir = (
        os.path.dirname(os.path.dirname(sys.executable))
        if getattr(sys, "frozen", False)
        else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )

    db_config = {
        "host": "YOUR_DB_HOST",
        "database": "YOUR_DB_NAME",
        "user": "YOUR_DB_USER",
        "password": "YOUR_DB_PASSWORD",
        "port": 5432,
        "sslmode": "require"
    }

    docuMateAgent = BirthRegistrationProcessor(
        db_config=db_config,
        template_path=os.path.join(base_dir, "templates", "DOCUMENT_TEMPLATE_FILE_MM.docx"),
        output_folder=os.path.join(base_dir, "output_files"),
        update_existing=False,
        auto_detect=True,
        poll_interval=30
    )

    # .start() instead of .run() -- start() decides whether to
    # run once or loop based on the auto_detect setting
    docuMateAgent.start()
